### PR TITLE
Uncharted LOTC PC Performance issue

### PR DESCRIPTION
**Pull request by jackbingow**
@GloriousEggroll On proton wine via steam performance is fine.above 15-20 fps.(Laptop)
On wine-ge-custom via lutis performance stutter,frame drops to 1-3fps.
Shader cache size is different 1,6 vs 7gb.
At wine-ge-custom no issues/pulls tab to report.

### CODE REVIEW

**Comment by GloriousEggroll** [comment]
proton-wine by itself is not meant to be used. it is used as a base for either wine-ge or proton-ge with several patches added to it. as proton-ge and wine-ge both work as intended in their associated releases I am closing this pr.

**Comment by GloriousEggroll** [comment]
-edit-

I misread the description. uncharted is a steam game only afaik. have you tested this in the latest proton-ge?

**Comment by jackbingow** [comment]
GE-Proton7-38 works fine
Wine-GE-Proton7-35 and earlier stuttering.(equivalent of lastest) on lutris.
Wine-GE-Proton7-33 same results.

**Comment by GloriousEggroll** [comment]
> GE-Proton7-38 works fine Wine-GE-Proton7-35 and earlier stuttering.(equivalent of lastest) on lutris. Wine-GE-Proton7-33 same results.

Again:

uncharted is a steam game only afaik. have you tested this in the latest proton-ge?

pirated games are not supported.

**Comment by jackbingow** [comment]
@GloriousEggroll Forgot to mention it's epic version.
[https://store.epicgames.com/en-US/p/uncharted-legacy-of-thieves-collection](https://store.epicgames.com/en-US/p/uncharted-legacy-of-thieves-collection)
not only steam exists.

I don't if proton for epic game launcher exists as in steam.

**Comment by GloriousEggroll** [comment]
please do not open bug reports here. I have issues closed intentionally. as noted in several of my repositories if there is an issue it should be reported in discord. additionally wine-ge does not include dxvk/vkd3d unlike proton-ge which includes it. if there is a performance issue it is in one of those, not wine-ge.

**Pull request closed without merging**
